spring:
    application:
        name: backend
    datasource:
        url: jdbc:h2:mem:/api 
        username: ${ADMIN_LOGIN:admin@admin.com}
        password: ${ADMIN_PASS:admin}
    jpa:
      hibernate:
        ddl-auto: update

api:
 security:
    token:
        secret: ${JTW_SECRET:my-secret-key}